### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by patdx** [patdx/rqlite-js#1]
- [x] get unit tests working
- [x] get integration tests working
- [x] add Github Actions
- [x] support fetch and worker environments
- [x] built in support for sql-template-tags
- [ ] pass through ky options directly
- [ ] fix stream support
- [ ] support generics, eg: `client.query<User>(toRqliteQuery(sql\`select id, username from app_user\`)),`
- [ ] support automatic integration with sql-template-tags
- [ ] make the types serialize more nicely: ![image](https://user-images.githubusercontent.com/353863/198268079-fd4320a2-1652-41cb-8eeb-ace5c84e30b5.png)
- [ ] fix skipped tests

Low priority:

- [ ] support unit tests and integration tests with both compiled and source files
